# Leitura do conjunto de dados

In [1]:
import pandas as pd

data_train = pd.read_csv("./mobile_train.csv")
data_train.tail()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[5 rows x 21 columns]

# Preprocessamento
### Separação dos dados de entrada e saída
* Quais features serão as feature de entrada? (x)
* Qual a features que vamos tentar prever? (y)

In [2]:
train_x = data_train.values[..., :20]
train_y = data_train.values[..., -1]

print("max:", train_x.max(), "min:",  train_x.min())
print(train_x.shape)
print(train_y.shape)
print(train_y)

max: 3998.0 min: 0.0
(2000, 20)
(2000,)
[1. 2. 2. ... 3. 0. 3.]


# Preprocessamento
### normalização dos valores
* Qual preprocessamento aplicado na entrada? (x)
* Qual preprocessamento aplicado na saída? (y)

In [3]:
from sklearn.preprocessing import MinMaxScaler
normalizer = MinMaxScaler()
train_x_normalized = normalizer.fit_transform(train_x)

print("max:", train_x_normalized.max(), "min:",  train_x_normalized.min())

max: 1.0000000000000002 min: 0.0


# One hot encoder
![One_Hot_Encoder](images/one_hot.png)

In [4]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
train_y_oh = ohe.fit_transform(train_y.reshape(-1, 1)).toarray()


print("train y:\n", train_y_oh)

train y:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


# Criação da rede neural com tensorflow.keras

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [6]:
model = Sequential()

model.add(Input(20))
model.add(Dense(32, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(4, activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                672       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 36        
Total params: 1,372
Trainable params: 1,372
Non-trainable params: 0
_________________________________________________________________


#### Compilação e treinamento

In [7]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_x_normalized, train_y_oh, epochs=100, batch_size=8, validation_split=0.2)

Epoch 1/100
200/200 [==============================] - 1s 6ms/step - loss: 1.3808 - accuracy: 0.2438 - val_loss: 1.3483 - val_accuracy: 0.2975
Epoch 2/100
200/200 [==============================] - 1s 3ms/step - loss: 1.2385 - accuracy: 0.3406 - val_loss: 1.0632 - val_accuracy: 0.3675
Epoch 3/100
200/200 [==============================] - 1s 3ms/step - loss: 0.8562 - accuracy: 0.6413 - val_loss: 0.6754 - val_accuracy: 0.7850
Epoch 4/100
200/200 [==============================] - 1s 3ms/step - loss: 0.5578 - accuracy: 0.8050 - val_loss: 0.5013 - val_accuracy: 0.8150
Epoch 5/100
200/200 [==============================] - 1s 3ms/step - loss: 0.4275 - accuracy: 0.8456 - val_loss: 0.3907 - val_accuracy: 0.8700
Epoch 6/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3503 - accuracy: 0.8756 - val_loss: 0.3345 - val_accuracy: 0.8800
Epoch 7/100
200/200 [==============================] - 1s 3ms/step - loss: 0.2997 - accuracy: 0.8963 - val_loss: 0.2906 - val_accuracy: 0.8925

200/200 [==============================] - 0s 943us/step - loss: 0.0470 - accuracy: 0.9875 - val_loss: 0.1907 - val_accuracy: 0.9175
Epoch 58/100
200/200 [==============================] - 0s 938us/step - loss: 0.0468 - accuracy: 0.9850 - val_loss: 0.1330 - val_accuracy: 0.9425
Epoch 59/100
200/200 [==============================] - 0s 943us/step - loss: 0.0506 - accuracy: 0.9831 - val_loss: 0.2085 - val_accuracy: 0.9250
Epoch 60/100
200/200 [==============================] - 0s 943us/step - loss: 0.0441 - accuracy: 0.9850 - val_loss: 0.1299 - val_accuracy: 0.9350
Epoch 61/100
200/200 [==============================] - 0s 938us/step - loss: 0.0520 - accuracy: 0.9825 - val_loss: 0.3271 - val_accuracy: 0.8900
Epoch 62/100
200/200 [==============================] - 0s 943us/step - loss: 0.0542 - accuracy: 0.9794 - val_loss: 0.1556 - val_accuracy: 0.9400
Epoch 63/100
200/200 [==============================] - 0s 943us/step - loss: 0.0393 - accuracy: 0.9856 - val_loss: 0.1352 - val_accuracy

# Como salvar o melhor modelo da nossa rede neural?
* Nem sempre a ultima época de treinamento contém o melhor modelo.
* Salvando nosso modelo, podemos utilzar futuramente sem a necessidade de refazer o treino.

### Callbacks
* Um callback é um metódo que será executado em um momento especifico (ex: todo fim de época, salvaremos o modelo)

In [8]:
from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard
import os

os.makedirs("./models", exist_ok=True)
check_point_saver_best_acc = ModelCheckpoint("./models/best_acc_{val_accuracy}_{epoch}.h5", monitor='val_accuracy', 
                                             save_best_only=True, period=1, verbose=1)

tensorboard_cb = TensorBoard(log_dir="./logs", write_graph=True)    

In [9]:
model = Sequential()
model.add(Input(20))
model.add(Dense(4, activation="softmax"))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_x_normalized, train_y_oh, epochs=100, batch_size=8, validation_split=0.2,
         callbacks=[check_point_saver_best_acc, tensorboard_cb])

Epoch 1/100
  1/200 [..............................] - ETA: 0s - loss: 1.4055 - accuracy: 0.3750WARNING:tensorflow:From c:\repositorios\deep_learning_ets\.venv\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
172/200 [========================>.....] - ETA: 0s - loss: 1.4102 - accuracy: 0.2943
Epoch 00001: val_accuracy improved from -inf to 0.31750, saving model to ./models\best_acc_0.3174999952316284_1.h5
200/200 [==============================] - 0s 2ms/step - loss: 1.4080 - accuracy: 0.2944 - val_loss: 1.3949 - val_accuracy: 0.3175
Epoch 2/100
175/200 [=========================>....] - ETA: 0s - loss: 1.3709 - accuracy: 0.3236
Epoch 00002: val_accuracy improved from 0.31750 to 0.34000, saving model to ./models\best_acc_0.3400000035762787_2.h5
200/200 [==============================] - 0s 835us/step - lo

154/200 [======================>.......] - ETA: 0s - loss: 0.9806 - accuracy: 0.6550
Epoch 00023: val_accuracy did not improve from 0.63000
200/200 [==============================] - 0s 938us/step - loss: 0.9733 - accuracy: 0.6637 - val_loss: 0.9973 - val_accuracy: 0.6225
Epoch 24/100
196/200 [============================>.] - ETA: 0s - loss: 0.9641 - accuracy: 0.6677
Epoch 00024: val_accuracy did not improve from 0.63000
200/200 [==============================] - 0s 1ms/step - loss: 0.9628 - accuracy: 0.6675 - val_loss: 0.9893 - val_accuracy: 0.6250
Epoch 25/100
133/200 [==================>...........] - ETA: 0s - loss: 0.9507 - accuracy: 0.6645
Epoch 00025: val_accuracy did not improve from 0.63000
200/200 [==============================] - 0s 992us/step - loss: 0.9526 - accuracy: 0.6719 - val_loss: 0.9812 - val_accuracy: 0.6125
Epoch 26/100
140/200 [====================>.........] - ETA: 0s - loss: 0.9383 - accuracy: 0.6714
Epoch 00026: val_accuracy improved from 0.63000 to 0.64250,

154/200 [======================>.......] - ETA: 0s - loss: 0.7800 - accuracy: 0.7435
Epoch 00050: val_accuracy improved from 0.70500 to 0.71250, saving model to ./models\best_acc_0.7124999761581421_50.h5
200/200 [==============================] - 0s 923us/step - loss: 0.7873 - accuracy: 0.7387 - val_loss: 0.8191 - val_accuracy: 0.7125
Epoch 51/100
145/200 [====================>.........] - ETA: 0s - loss: 0.7750 - accuracy: 0.7440
Epoch 00051: val_accuracy improved from 0.71250 to 0.72250, saving model to ./models\best_acc_0.7225000262260437_51.h5
200/200 [==============================] - 0s 1ms/step - loss: 0.7824 - accuracy: 0.7425 - val_loss: 0.8139 - val_accuracy: 0.7225
Epoch 52/100
188/200 [===========================>..] - ETA: 0s - loss: 0.7790 - accuracy: 0.7540
Epoch 00052: val_accuracy did not improve from 0.72250
200/200 [==============================] - 0s 1ms/step - loss: 0.7784 - accuracy: 0.7519 - val_loss: 0.8094 - val_accuracy: 0.7200
Epoch 53/100
200/200 [=========

Epoch 77/100
141/200 [====================>.........] - ETA: 0s - loss: 0.6995 - accuracy: 0.7793
Epoch 00077: val_accuracy did not improve from 0.76250
200/200 [==============================] - 0s 957us/step - loss: 0.6904 - accuracy: 0.7850 - val_loss: 0.7224 - val_accuracy: 0.7600
Epoch 78/100
134/200 [===================>..........] - ETA: 0s - loss: 0.7001 - accuracy: 0.7705
Epoch 00078: val_accuracy improved from 0.76250 to 0.76500, saving model to ./models\best_acc_0.7649999856948853_78.h5
200/200 [==============================] - 0s 1ms/step - loss: 0.6873 - accuracy: 0.7856 - val_loss: 0.7199 - val_accuracy: 0.7650
Epoch 79/100
157/200 [======================>.......] - ETA: 0s - loss: 0.6824 - accuracy: 0.7914
Epoch 00079: val_accuracy improved from 0.76500 to 0.77000, saving model to ./models\best_acc_0.7699999809265137_79.h5
200/200 [==============================] - 0s 918us/step - loss: 0.6841 - accuracy: 0.7881 - val_loss: 0.7172 - val_accuracy: 0.7700
Epoch 80/100
146

In [10]:
model.save("./models/my_last_epoch_model.h5")

# Inferência
* Como carregar e utilizar um modelo treinado?

In [11]:
from tensorflow.keras.models import load_model

model = load_model("./models/my_last_epoch_model.h5")

#### Carregar dados de testes (Sem label de saída)

In [12]:
data_test = pd.read_csv("./mobile_test.csv")
test_x = data_test.values[..., 1:]
print(test_x.shape)

test_x_normalized = normalizer.transform(test_x)

(1000, 20)


In [13]:
import numpy as np
pred_y = model.predict(test_x_normalized)
print(pred_y)
print(np.round(pred_y))

[[5.1635288e-04 4.2644490e-02 4.2655706e-01 5.3028202e-01]
 [2.0590096e-04 6.3739389e-02 4.3546784e-01 5.0058687e-01]
 [1.5615023e-02 3.4362218e-01 3.2567388e-01 3.1508884e-01]
 ...
 [1.7765015e-01 4.6321824e-01 2.6919729e-01 8.9934409e-02]
 [2.3116447e-02 2.6907814e-01 4.1089186e-01 2.9691356e-01]
 [4.2133997e-03 1.2177369e-01 5.5932248e-01 3.1469041e-01]]
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
